import "./globals.css";
import { Suspense } from "react";
import { AuthProvider } from "../lib/AuthContext";
import BottomNav from "./BottomNav";
import GoogleTranslate from "./GoogleTranslate";

export const metadata = {
  title: "RoomLink",
  description: "Generated by bartholome kwame yankey",
  manifest: "/manifest.json",
  themeColor: "#1E88E5",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
     <body className="min-h-full flex flex-col pb-16">
        <GoogleTranslate />
        <AuthProvider>
          {children}
          <Suspense fallback={null}>
            <BottomNav />
          </Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}