import "./globals.css";
import { Suspense } from "react";
import { AuthProvider } from "../lib/AuthContext";
import { ThemeProvider } from "../lib/ThemeContext";
import AuthGate from "./AuthGate";
import BottomNav from "./BottomNav";
import GoogleTranslate from "./GoogleTranslate";

export const metadata = {
  title: "HnAlink",
  description: "Generated by bartholome kwame yankey",
  manifest: "/manifest.json",
  themeColor: "#1E88E5",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
     <body className="min-h-full flex flex-col pb-16">
        <GoogleTranslate />
        <ThemeProvider>
          <AuthProvider>
            <Suspense fallback={null}>
              <AuthGate>{children}</AuthGate>
            </Suspense>
            <Suspense fallback={null}>
              <BottomNav />
            </Suspense>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}